BEGIN;

CREATE TABLE IF NOT EXISTS recordatorios (
    id_recordatorio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tarea INTEGER NOT NULL,
    fecha_recordatorio TIMESTAMP NOT NULL,
    mensaje VARCHAR(255) NOT NULL,
    enviado BOOLEAN NOT NULL DEFAULT FALSE
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_recordatorios_tareas'
    ) THEN
        ALTER TABLE recordatorios
            ADD CONSTRAINT fk_recordatorios_tareas
            FOREIGN KEY (id_tarea)
            REFERENCES tareas (id_tarea)
            ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_recordatorios_id_tarea
    ON recordatorios (id_tarea);

COMMIT;
